package dataawsccapplicationautoscalingscalingpolicy


type DataAwsccApplicationautoscalingScalingPolicyPredictiveScalingPolicyConfigurationMetricSpecificationsPredefinedMetricPairSpecification struct {
}

