package dataawsccapplicationautoscalingscalingpolicy


type DataAwsccApplicationautoscalingScalingPolicyTargetTrackingScalingPolicyConfigurationCustomizedMetricSpecificationMetricsMetricStatMetricDimensions struct {
}

