package dataawsccapplicationsignalsservicelevelobjective


type DataAwsccApplicationsignalsServiceLevelObjectiveRequestBasedSliRequestBasedSliMetricMonitoredRequestCountMetricBadCountMetricMetricStat struct {
}

