package dataawsccapplicationsignalsservicelevelobjective


type DataAwsccApplicationsignalsServiceLevelObjectiveRequestBasedSliRequestBasedSliMetricMonitoredRequestCountMetricGoodCountMetric struct {
}

