//go:build no_runtime_type_checking

package dataawsccmediapackagepackagingconfiguration

// Building without runtime type checking enabled, so all the below just return nil

func (d *jsiiProxy_DataAwsccMediapackagePackagingConfigurationMssPackageMssManifestsStreamSelectionOutputReference) validateGetAnyMapAttributeParameters(terraformAttribute *string) error {
	return nil
}

func (d *jsiiProxy_DataAwsccMediapackagePackagingConfigurationMssPackageMssManifestsStreamSelectionOutputReference) validateGetBooleanAttributeParameters(terraformAttribute *string) error {
	return nil
}

func (d *jsiiProxy_DataAwsccMediapackagePackagingConfigurationMssPackageMssManifestsStreamSelectionOutputReference) validateGetBooleanMapAttributeParameters(terraformAttribute *string) error {
	return nil
}

func (d *jsiiProxy_DataAwsccMediapackagePackagingConfigurationMssPackageMssManifestsStreamSelectionOutputReference) validateGetListAttributeParameters(terraformAttribute *string) error {
	return nil
}

func (d *jsiiProxy_DataAwsccMediapackagePackagingConfigurationMssPackageMssManifestsStreamSelectionOutputReference) validateGetNumberAttributeParameters(terraformAttribute *string) error {
	return nil
}

func (d *jsiiProxy_DataAwsccMediapackagePackagingConfigurationMssPackageMssManifestsStreamSelectionOutputReference) validateGetNumberListAttributeParameters(terraformAttribute *string) error {
	return nil
}

func (d *jsiiProxy_DataAwsccMediapackagePackagingConfigurationMssPackageMssManifestsStreamSelectionOutputReference) validateGetNumberMapAttributeParameters(terraformAttribute *string) error {
	return nil
}

func (d *jsiiProxy_DataAwsccMediapackagePackagingConfigurationMssPackageMssManifestsStreamSelectionOutputReference) validateGetStringAttributeParameters(terraformAttribute *string) error {
	return nil
}

func (d *jsiiProxy_DataAwsccMediapackagePackagingConfigurationMssPackageMssManifestsStreamSelectionOutputReference) validateGetStringMapAttributeParameters(terraformAttribute *string) error {
	return nil
}

func (d *jsiiProxy_DataAwsccMediapackagePackagingConfigurationMssPackageMssManifestsStreamSelectionOutputReference) validateInterpolationForAttributeParameters(property *string) error {
	return nil
}

func (d *jsiiProxy_DataAwsccMediapackagePackagingConfigurationMssPackageMssManifestsStreamSelectionOutputReference) validateResolveParameters(_context cdktf.IResolveContext) error {
	return nil
}

func (j *jsiiProxy_DataAwsccMediapackagePackagingConfigurationMssPackageMssManifestsStreamSelectionOutputReference) validateSetComplexObjectIndexParameters(val interface{}) error {
	return nil
}

func (j *jsiiProxy_DataAwsccMediapackagePackagingConfigurationMssPackageMssManifestsStreamSelectionOutputReference) validateSetComplexObjectIsFromSetParameters(val *bool) error {
	return nil
}

func (j *jsiiProxy_DataAwsccMediapackagePackagingConfigurationMssPackageMssManifestsStreamSelectionOutputReference) validateSetInternalValueParameters(val *DataAwsccMediapackagePackagingConfigurationMssPackageMssManifestsStreamSelection) error {
	return nil
}

func (j *jsiiProxy_DataAwsccMediapackagePackagingConfigurationMssPackageMssManifestsStreamSelectionOutputReference) validateSetTerraformAttributeParameters(val *string) error {
	return nil
}

func (j *jsiiProxy_DataAwsccMediapackagePackagingConfigurationMssPackageMssManifestsStreamSelectionOutputReference) validateSetTerraformResourceParameters(val cdktf.IInterpolatingParent) error {
	return nil
}

func validateNewDataAwsccMediapackagePackagingConfigurationMssPackageMssManifestsStreamSelectionOutputReferenceParameters(terraformResource cdktf.IInterpolatingParent, terraformAttribute *string) error {
	return nil
}

