//go:build no_runtime_type_checking

package dataawscccloudfrontdistribution

// Building without runtime type checking enabled, so all the below just return nil

func (d *jsiiProxy_DataAwsccCloudfrontDistributionDistributionConfigCacheBehaviorsLambdaFunctionAssociationsOutputReference) validateGetAnyMapAttributeParameters(terraformAttribute *string) error {
	return nil
}

func (d *jsiiProxy_DataAwsccCloudfrontDistributionDistributionConfigCacheBehaviorsLambdaFunctionAssociationsOutputReference) validateGetBooleanAttributeParameters(terraformAttribute *string) error {
	return nil
}

func (d *jsiiProxy_DataAwsccCloudfrontDistributionDistributionConfigCacheBehaviorsLambdaFunctionAssociationsOutputReference) validateGetBooleanMapAttributeParameters(terraformAttribute *string) error {
	return nil
}

func (d *jsiiProxy_DataAwsccCloudfrontDistributionDistributionConfigCacheBehaviorsLambdaFunctionAssociationsOutputReference) validateGetListAttributeParameters(terraformAttribute *string) error {
	return nil
}

func (d *jsiiProxy_DataAwsccCloudfrontDistributionDistributionConfigCacheBehaviorsLambdaFunctionAssociationsOutputReference) validateGetNumberAttributeParameters(terraformAttribute *string) error {
	return nil
}

func (d *jsiiProxy_DataAwsccCloudfrontDistributionDistributionConfigCacheBehaviorsLambdaFunctionAssociationsOutputReference) validateGetNumberListAttributeParameters(terraformAttribute *string) error {
	return nil
}

func (d *jsiiProxy_DataAwsccCloudfrontDistributionDistributionConfigCacheBehaviorsLambdaFunctionAssociationsOutputReference) validateGetNumberMapAttributeParameters(terraformAttribute *string) error {
	return nil
}

func (d *jsiiProxy_DataAwsccCloudfrontDistributionDistributionConfigCacheBehaviorsLambdaFunctionAssociationsOutputReference) validateGetStringAttributeParameters(terraformAttribute *string) error {
	return nil
}

func (d *jsiiProxy_DataAwsccCloudfrontDistributionDistributionConfigCacheBehaviorsLambdaFunctionAssociationsOutputReference) validateGetStringMapAttributeParameters(terraformAttribute *string) error {
	return nil
}

func (d *jsiiProxy_DataAwsccCloudfrontDistributionDistributionConfigCacheBehaviorsLambdaFunctionAssociationsOutputReference) validateInterpolationForAttributeParameters(property *string) error {
	return nil
}

func (d *jsiiProxy_DataAwsccCloudfrontDistributionDistributionConfigCacheBehaviorsLambdaFunctionAssociationsOutputReference) validateResolveParameters(_context cdktf.IResolveContext) error {
	return nil
}

func (j *jsiiProxy_DataAwsccCloudfrontDistributionDistributionConfigCacheBehaviorsLambdaFunctionAssociationsOutputReference) validateSetComplexObjectIndexParameters(val interface{}) error {
	return nil
}

func (j *jsiiProxy_DataAwsccCloudfrontDistributionDistributionConfigCacheBehaviorsLambdaFunctionAssociationsOutputReference) validateSetComplexObjectIsFromSetParameters(val *bool) error {
	return nil
}

func (j *jsiiProxy_DataAwsccCloudfrontDistributionDistributionConfigCacheBehaviorsLambdaFunctionAssociationsOutputReference) validateSetInternalValueParameters(val *DataAwsccCloudfrontDistributionDistributionConfigCacheBehaviorsLambdaFunctionAssociations) error {
	return nil
}

func (j *jsiiProxy_DataAwsccCloudfrontDistributionDistributionConfigCacheBehaviorsLambdaFunctionAssociationsOutputReference) validateSetTerraformAttributeParameters(val *string) error {
	return nil
}

func (j *jsiiProxy_DataAwsccCloudfrontDistributionDistributionConfigCacheBehaviorsLambdaFunctionAssociationsOutputReference) validateSetTerraformResourceParameters(val cdktf.IInterpolatingParent) error {
	return nil
}

func validateNewDataAwsccCloudfrontDistributionDistributionConfigCacheBehaviorsLambdaFunctionAssociationsOutputReferenceParameters(terraformResource cdktf.IInterpolatingParent, terraformAttribute *string, complexObjectIndex *float64, complexObjectIsFromSet *bool) error {
	return nil
}

