package dataawscccloudfrontcontinuousdeploymentpolicy


type DataAwsccCloudfrontContinuousDeploymentPolicyContinuousDeploymentPolicyConfigTrafficConfigSingleWeightConfigSessionStickinessConfig struct {
}

