//go:build no_runtime_type_checking

package dataawsccbedrockdataautomationproject

// Building without runtime type checking enabled, so all the below just return nil

func (d *jsiiProxy_DataAwsccBedrockDataAutomationProjectStandardOutputConfigurationImageExtractionBoundingBoxOutputReference) validateGetAnyMapAttributeParameters(terraformAttribute *string) error {
	return nil
}

func (d *jsiiProxy_DataAwsccBedrockDataAutomationProjectStandardOutputConfigurationImageExtractionBoundingBoxOutputReference) validateGetBooleanAttributeParameters(terraformAttribute *string) error {
	return nil
}

func (d *jsiiProxy_DataAwsccBedrockDataAutomationProjectStandardOutputConfigurationImageExtractionBoundingBoxOutputReference) validateGetBooleanMapAttributeParameters(terraformAttribute *string) error {
	return nil
}

func (d *jsiiProxy_DataAwsccBedrockDataAutomationProjectStandardOutputConfigurationImageExtractionBoundingBoxOutputReference) validateGetListAttributeParameters(terraformAttribute *string) error {
	return nil
}

func (d *jsiiProxy_DataAwsccBedrockDataAutomationProjectStandardOutputConfigurationImageExtractionBoundingBoxOutputReference) validateGetNumberAttributeParameters(terraformAttribute *string) error {
	return nil
}

func (d *jsiiProxy_DataAwsccBedrockDataAutomationProjectStandardOutputConfigurationImageExtractionBoundingBoxOutputReference) validateGetNumberListAttributeParameters(terraformAttribute *string) error {
	return nil
}

func (d *jsiiProxy_DataAwsccBedrockDataAutomationProjectStandardOutputConfigurationImageExtractionBoundingBoxOutputReference) validateGetNumberMapAttributeParameters(terraformAttribute *string) error {
	return nil
}

func (d *jsiiProxy_DataAwsccBedrockDataAutomationProjectStandardOutputConfigurationImageExtractionBoundingBoxOutputReference) validateGetStringAttributeParameters(terraformAttribute *string) error {
	return nil
}

func (d *jsiiProxy_DataAwsccBedrockDataAutomationProjectStandardOutputConfigurationImageExtractionBoundingBoxOutputReference) validateGetStringMapAttributeParameters(terraformAttribute *string) error {
	return nil
}

func (d *jsiiProxy_DataAwsccBedrockDataAutomationProjectStandardOutputConfigurationImageExtractionBoundingBoxOutputReference) validateInterpolationForAttributeParameters(property *string) error {
	return nil
}

func (d *jsiiProxy_DataAwsccBedrockDataAutomationProjectStandardOutputConfigurationImageExtractionBoundingBoxOutputReference) validateResolveParameters(_context cdktf.IResolveContext) error {
	return nil
}

func (j *jsiiProxy_DataAwsccBedrockDataAutomationProjectStandardOutputConfigurationImageExtractionBoundingBoxOutputReference) validateSetComplexObjectIndexParameters(val interface{}) error {
	return nil
}

func (j *jsiiProxy_DataAwsccBedrockDataAutomationProjectStandardOutputConfigurationImageExtractionBoundingBoxOutputReference) validateSetComplexObjectIsFromSetParameters(val *bool) error {
	return nil
}

func (j *jsiiProxy_DataAwsccBedrockDataAutomationProjectStandardOutputConfigurationImageExtractionBoundingBoxOutputReference) validateSetInternalValueParameters(val *DataAwsccBedrockDataAutomationProjectStandardOutputConfigurationImageExtractionBoundingBox) error {
	return nil
}

func (j *jsiiProxy_DataAwsccBedrockDataAutomationProjectStandardOutputConfigurationImageExtractionBoundingBoxOutputReference) validateSetTerraformAttributeParameters(val *string) error {
	return nil
}

func (j *jsiiProxy_DataAwsccBedrockDataAutomationProjectStandardOutputConfigurationImageExtractionBoundingBoxOutputReference) validateSetTerraformResourceParameters(val cdktf.IInterpolatingParent) error {
	return nil
}

func validateNewDataAwsccBedrockDataAutomationProjectStandardOutputConfigurationImageExtractionBoundingBoxOutputReferenceParameters(terraformResource cdktf.IInterpolatingParent, terraformAttribute *string) error {
	return nil
}

