//go:build no_runtime_type_checking

package bedrockpromptversion

// Building without runtime type checking enabled, so all the below just return nil

func (b *jsiiProxy_BedrockPromptVersionVariantsTemplateConfigurationChatToolConfigurationToolsCachePointOutputReference) validateGetAnyMapAttributeParameters(terraformAttribute *string) error {
	return nil
}

func (b *jsiiProxy_BedrockPromptVersionVariantsTemplateConfigurationChatToolConfigurationToolsCachePointOutputReference) validateGetBooleanAttributeParameters(terraformAttribute *string) error {
	return nil
}

func (b *jsiiProxy_BedrockPromptVersionVariantsTemplateConfigurationChatToolConfigurationToolsCachePointOutputReference) validateGetBooleanMapAttributeParameters(terraformAttribute *string) error {
	return nil
}

func (b *jsiiProxy_BedrockPromptVersionVariantsTemplateConfigurationChatToolConfigurationToolsCachePointOutputReference) validateGetListAttributeParameters(terraformAttribute *string) error {
	return nil
}

func (b *jsiiProxy_BedrockPromptVersionVariantsTemplateConfigurationChatToolConfigurationToolsCachePointOutputReference) validateGetNumberAttributeParameters(terraformAttribute *string) error {
	return nil
}

func (b *jsiiProxy_BedrockPromptVersionVariantsTemplateConfigurationChatToolConfigurationToolsCachePointOutputReference) validateGetNumberListAttributeParameters(terraformAttribute *string) error {
	return nil
}

func (b *jsiiProxy_BedrockPromptVersionVariantsTemplateConfigurationChatToolConfigurationToolsCachePointOutputReference) validateGetNumberMapAttributeParameters(terraformAttribute *string) error {
	return nil
}

func (b *jsiiProxy_BedrockPromptVersionVariantsTemplateConfigurationChatToolConfigurationToolsCachePointOutputReference) validateGetStringAttributeParameters(terraformAttribute *string) error {
	return nil
}

func (b *jsiiProxy_BedrockPromptVersionVariantsTemplateConfigurationChatToolConfigurationToolsCachePointOutputReference) validateGetStringMapAttributeParameters(terraformAttribute *string) error {
	return nil
}

func (b *jsiiProxy_BedrockPromptVersionVariantsTemplateConfigurationChatToolConfigurationToolsCachePointOutputReference) validateInterpolationForAttributeParameters(property *string) error {
	return nil
}

func (b *jsiiProxy_BedrockPromptVersionVariantsTemplateConfigurationChatToolConfigurationToolsCachePointOutputReference) validateResolveParameters(_context cdktf.IResolveContext) error {
	return nil
}

func (j *jsiiProxy_BedrockPromptVersionVariantsTemplateConfigurationChatToolConfigurationToolsCachePointOutputReference) validateSetComplexObjectIndexParameters(val interface{}) error {
	return nil
}

func (j *jsiiProxy_BedrockPromptVersionVariantsTemplateConfigurationChatToolConfigurationToolsCachePointOutputReference) validateSetComplexObjectIsFromSetParameters(val *bool) error {
	return nil
}

func (j *jsiiProxy_BedrockPromptVersionVariantsTemplateConfigurationChatToolConfigurationToolsCachePointOutputReference) validateSetInternalValueParameters(val *BedrockPromptVersionVariantsTemplateConfigurationChatToolConfigurationToolsCachePoint) error {
	return nil
}

func (j *jsiiProxy_BedrockPromptVersionVariantsTemplateConfigurationChatToolConfigurationToolsCachePointOutputReference) validateSetTerraformAttributeParameters(val *string) error {
	return nil
}

func (j *jsiiProxy_BedrockPromptVersionVariantsTemplateConfigurationChatToolConfigurationToolsCachePointOutputReference) validateSetTerraformResourceParameters(val cdktf.IInterpolatingParent) error {
	return nil
}

func validateNewBedrockPromptVersionVariantsTemplateConfigurationChatToolConfigurationToolsCachePointOutputReferenceParameters(terraformResource cdktf.IInterpolatingParent, terraformAttribute *string) error {
	return nil
}

