package dataawsccbedrockdatasource


type DataAwsccBedrockDataSourceVectorIngestionConfigurationCustomTransformationConfigurationTransformationsTransformationFunctionTransformationLambdaConfiguration struct {
}

