//go:build no_runtime_type_checking

package dataawscclexbot

// Building without runtime type checking enabled, so all the below just return nil

func (d *jsiiProxy_DataAwsccLexBotTestBotAliasSettingsConversationLogSettingsAudioLogSettingsDestinationOutputReference) validateGetAnyMapAttributeParameters(terraformAttribute *string) error {
	return nil
}

func (d *jsiiProxy_DataAwsccLexBotTestBotAliasSettingsConversationLogSettingsAudioLogSettingsDestinationOutputReference) validateGetBooleanAttributeParameters(terraformAttribute *string) error {
	return nil
}

func (d *jsiiProxy_DataAwsccLexBotTestBotAliasSettingsConversationLogSettingsAudioLogSettingsDestinationOutputReference) validateGetBooleanMapAttributeParameters(terraformAttribute *string) error {
	return nil
}

func (d *jsiiProxy_DataAwsccLexBotTestBotAliasSettingsConversationLogSettingsAudioLogSettingsDestinationOutputReference) validateGetListAttributeParameters(terraformAttribute *string) error {
	return nil
}

func (d *jsiiProxy_DataAwsccLexBotTestBotAliasSettingsConversationLogSettingsAudioLogSettingsDestinationOutputReference) validateGetNumberAttributeParameters(terraformAttribute *string) error {
	return nil
}

func (d *jsiiProxy_DataAwsccLexBotTestBotAliasSettingsConversationLogSettingsAudioLogSettingsDestinationOutputReference) validateGetNumberListAttributeParameters(terraformAttribute *string) error {
	return nil
}

func (d *jsiiProxy_DataAwsccLexBotTestBotAliasSettingsConversationLogSettingsAudioLogSettingsDestinationOutputReference) validateGetNumberMapAttributeParameters(terraformAttribute *string) error {
	return nil
}

func (d *jsiiProxy_DataAwsccLexBotTestBotAliasSettingsConversationLogSettingsAudioLogSettingsDestinationOutputReference) validateGetStringAttributeParameters(terraformAttribute *string) error {
	return nil
}

func (d *jsiiProxy_DataAwsccLexBotTestBotAliasSettingsConversationLogSettingsAudioLogSettingsDestinationOutputReference) validateGetStringMapAttributeParameters(terraformAttribute *string) error {
	return nil
}

func (d *jsiiProxy_DataAwsccLexBotTestBotAliasSettingsConversationLogSettingsAudioLogSettingsDestinationOutputReference) validateInterpolationForAttributeParameters(property *string) error {
	return nil
}

func (d *jsiiProxy_DataAwsccLexBotTestBotAliasSettingsConversationLogSettingsAudioLogSettingsDestinationOutputReference) validateResolveParameters(_context cdktf.IResolveContext) error {
	return nil
}

func (j *jsiiProxy_DataAwsccLexBotTestBotAliasSettingsConversationLogSettingsAudioLogSettingsDestinationOutputReference) validateSetComplexObjectIndexParameters(val interface{}) error {
	return nil
}

func (j *jsiiProxy_DataAwsccLexBotTestBotAliasSettingsConversationLogSettingsAudioLogSettingsDestinationOutputReference) validateSetComplexObjectIsFromSetParameters(val *bool) error {
	return nil
}

func (j *jsiiProxy_DataAwsccLexBotTestBotAliasSettingsConversationLogSettingsAudioLogSettingsDestinationOutputReference) validateSetInternalValueParameters(val *DataAwsccLexBotTestBotAliasSettingsConversationLogSettingsAudioLogSettingsDestination) error {
	return nil
}

func (j *jsiiProxy_DataAwsccLexBotTestBotAliasSettingsConversationLogSettingsAudioLogSettingsDestinationOutputReference) validateSetTerraformAttributeParameters(val *string) error {
	return nil
}

func (j *jsiiProxy_DataAwsccLexBotTestBotAliasSettingsConversationLogSettingsAudioLogSettingsDestinationOutputReference) validateSetTerraformResourceParameters(val cdktf.IInterpolatingParent) error {
	return nil
}

func validateNewDataAwsccLexBotTestBotAliasSettingsConversationLogSettingsAudioLogSettingsDestinationOutputReferenceParameters(terraformResource cdktf.IInterpolatingParent, terraformAttribute *string) error {
	return nil
}

