//go:build no_runtime_type_checking

package dataawsccimagebuilderdistributionconfiguration

// Building without runtime type checking enabled, so all the below just return nil

func (d *jsiiProxy_DataAwsccImagebuilderDistributionConfigurationDistributionsContainerDistributionConfigurationOutputReference) validateGetAnyMapAttributeParameters(terraformAttribute *string) error {
	return nil
}

func (d *jsiiProxy_DataAwsccImagebuilderDistributionConfigurationDistributionsContainerDistributionConfigurationOutputReference) validateGetBooleanAttributeParameters(terraformAttribute *string) error {
	return nil
}

func (d *jsiiProxy_DataAwsccImagebuilderDistributionConfigurationDistributionsContainerDistributionConfigurationOutputReference) validateGetBooleanMapAttributeParameters(terraformAttribute *string) error {
	return nil
}

func (d *jsiiProxy_DataAwsccImagebuilderDistributionConfigurationDistributionsContainerDistributionConfigurationOutputReference) validateGetListAttributeParameters(terraformAttribute *string) error {
	return nil
}

func (d *jsiiProxy_DataAwsccImagebuilderDistributionConfigurationDistributionsContainerDistributionConfigurationOutputReference) validateGetNumberAttributeParameters(terraformAttribute *string) error {
	return nil
}

func (d *jsiiProxy_DataAwsccImagebuilderDistributionConfigurationDistributionsContainerDistributionConfigurationOutputReference) validateGetNumberListAttributeParameters(terraformAttribute *string) error {
	return nil
}

func (d *jsiiProxy_DataAwsccImagebuilderDistributionConfigurationDistributionsContainerDistributionConfigurationOutputReference) validateGetNumberMapAttributeParameters(terraformAttribute *string) error {
	return nil
}

func (d *jsiiProxy_DataAwsccImagebuilderDistributionConfigurationDistributionsContainerDistributionConfigurationOutputReference) validateGetStringAttributeParameters(terraformAttribute *string) error {
	return nil
}

func (d *jsiiProxy_DataAwsccImagebuilderDistributionConfigurationDistributionsContainerDistributionConfigurationOutputReference) validateGetStringMapAttributeParameters(terraformAttribute *string) error {
	return nil
}

func (d *jsiiProxy_DataAwsccImagebuilderDistributionConfigurationDistributionsContainerDistributionConfigurationOutputReference) validateInterpolationForAttributeParameters(property *string) error {
	return nil
}

func (d *jsiiProxy_DataAwsccImagebuilderDistributionConfigurationDistributionsContainerDistributionConfigurationOutputReference) validateResolveParameters(_context cdktf.IResolveContext) error {
	return nil
}

func (j *jsiiProxy_DataAwsccImagebuilderDistributionConfigurationDistributionsContainerDistributionConfigurationOutputReference) validateSetComplexObjectIndexParameters(val interface{}) error {
	return nil
}

func (j *jsiiProxy_DataAwsccImagebuilderDistributionConfigurationDistributionsContainerDistributionConfigurationOutputReference) validateSetComplexObjectIsFromSetParameters(val *bool) error {
	return nil
}

func (j *jsiiProxy_DataAwsccImagebuilderDistributionConfigurationDistributionsContainerDistributionConfigurationOutputReference) validateSetInternalValueParameters(val *DataAwsccImagebuilderDistributionConfigurationDistributionsContainerDistributionConfiguration) error {
	return nil
}

func (j *jsiiProxy_DataAwsccImagebuilderDistributionConfigurationDistributionsContainerDistributionConfigurationOutputReference) validateSetTerraformAttributeParameters(val *string) error {
	return nil
}

func (j *jsiiProxy_DataAwsccImagebuilderDistributionConfigurationDistributionsContainerDistributionConfigurationOutputReference) validateSetTerraformResourceParameters(val cdktf.IInterpolatingParent) error {
	return nil
}

func validateNewDataAwsccImagebuilderDistributionConfigurationDistributionsContainerDistributionConfigurationOutputReferenceParameters(terraformResource cdktf.IInterpolatingParent, terraformAttribute *string) error {
	return nil
}

