name: Build Test
on:
  pull_request:
    branches:
      - "**"

jobs:
  BuildTest:
    runs-on: ubuntu-latest

    permissions:
      contents: write

    steps:
      - uses: actions/checkout@v4
        with:
          # pull the entire branch so we can commit back to it
          ref: ${{ github.event.pull_request.head.ref }}

      - name: Set up Go
        uses: actions/setup-go@v4
        with:
          go-version-file: go.mod

      - uses: actions/setup-node@v4
        with:
          node-version: 20

      - name: Install dependencies
        run: yarn install

      - name: Generate module and provider bindings
        run: npx cdktf-cli get

      - uses: EndBug/add-and-commit@v9
        with:
          default_author: github_actions
